version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/muhammednagy/PR-519-Software-development-project-backend"]

[[analyzers]]
name = "docker"
enabled = true
